### ISSUE TITLE
Может в константу?

### ISSUE THREAD

**Issue by Sibiya666** [fed-a/my-nextjs-blog#4]
https://github.com/fed-a/my-nextjs-blog/blob/d5d74b2ee3fb670f55fcd62d5bd55366b8280b00/scripts/update-graphql.js#L11

**Comment by fed-a** [comment]
А, этот файл как-то больше не нужен, потому что я не стал Аполловскую реализацию клиента на некст JS использовать. Как-то лучше себя проявил самописный getClient().
Удалю файл))
