### ISSUE TITLE
В рамках некса такое держим в компонентах так как  это серверные компоненты?

### ISSUE THREAD

**Issue by Sibiya666** [fed-a/my-nextjs-blog#6]
https://github.com/fed-a/my-nextjs-blog/blob/d5d74b2ee3fb670f55fcd62d5bd55366b8280b00/src/app/%5Blocale%5D/blog/%5Bslug%5D/page.tsx#L22

**Comment by fed-a** [comment]
Да, если не хотим в рантайме это. А я вот как раз думаю, что все тексты, локализации должны быть уже в HTML на этапе загрузки. Но тогда нам нужен серверный компонент, потому что клиентский компонент не поддерживает await. Тут можно еще раз подумать, как это доставать и сделать это покрасивее))
