### ISSUE TITLE
Это особенность некста? можно ли привязаться к роутеру и там прогружать в конфиг?

### ISSUE THREAD

**Issue by Sibiya666** [fed-a/my-nextjs-blog#7]
https://github.com/fed-a/my-nextjs-blog/blob/d5d74b2ee3fb670f55fcd62d5bd55366b8280b00/src/app/%5Blocale%5D/ui-kit/page.tsx#L17

**Comment by fed-a** [comment]
Оказывается да)
https://github.com/vercel/next.js/issues/8974
Перепишу

**Comment by fed-a** [comment]
А, оказывается нет)
![image](https://github.com/fed-a/my-nextjs-blog/assets/15703348/bd3245b9-a082-4a34-a44f-7f60a2e32002)
