### ISSUE TITLE
Списки в константы?

### ISSUE THREAD

**Issue by Sibiya666** [fed-a/my-nextjs-blog#9]
https://github.com/fed-a/my-nextjs-blog/blob/d5d74b2ee3fb670f55fcd62d5bd55366b8280b00/src/app/%5Blocale%5D/page.tsx#L20

**Comment by fed-a** [comment]
Тут скорее стоит посмотреть, что получилось с локализацией и переписать ее.

Сначала я думал писать что-то вроде `l('blog.sort')`. А потом оказалось, что это так просто не работает. Я бы изменение локализации в TODO занес
